package blockchain

const (
	BLOCKCHAIN_PORT_RANGE_START       = 5000
	BLOCKCHAIN_PORT_RANGE_END         = 5003
	NEIGHBOR_IP_RANGE_START           = 0
	NEIGHBOR_IP_RANGE_END             = 0
	BLOCKCHAIN_NEIGHBOR_SYNC_TIME_SEC = 5
)
